source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DLCollectionViewWaterfallLayout_Example' do
  pod 'DLCollectionViewWaterfallLayout', :path => '../'
  pod 'MJRefresh'

  target 'DLCollectionViewWaterfallLayout_Tests' do
    inherit! :search_paths

    
  end
end
